### ISSUE TITLE
load sqlrelay dynamic library php

### ISSUE THREAD

**Issue by moses-gangipogu** [MoonFantasy/pdo_sqlrelay#1]
I am try to install and use sqlrelay with php pdo mysql in Debian 7.1 wheezy

the steps that i followed

`first download sqlrealy and rudiments`

`Tar vxzf rudiments-0.28.2.tar.gz  
   Cd rudiments-0.28.2  
  . / Configure – prefix = /usr/local/rudiments  
   Make  
   Make install`

`Tar vxzf sqlrelay-0.36.4.tar.gz`

`Cd sqlrelay-0.36.4`

`apt-get install php5-dev`

 `./configure --prefix=/usr/local/sqlrelay --with-rudiments-prefix=/usr/local/rudiments`

 then i got this output

```
        ***** Summary ***********************************************
         Version      : 0.57

         Command Line : Readline Support          no


         APIs         : C/C++       yes           Perl       yes
                        Python      no            Ruby       no
                        PHP         yes           Java       yes
                        PHP PDO     yes           ODBC       no
                        TCL         no            Erlang     no

         Connections  : Oracle8     no            MySQL      dynamic
                        PostgreSQL  no            SQLite     no
                        FreeTDS     no            Sybase     no
                        ODBC        no            DB2        no
                        Firebird    no            MDB Tools  no
        *************************************************************
```

   `Make`

   `Make install`

`extension=pdo_sqlrelay.so in php.ini and finally restart apache2`

but while restating apache2 i get this error
in apache2 error.log

`[] [notice] caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/pdo_sqlrelay.so' - /usr/lib/php5/20100525/pdo_sqlrelay.so: undefined symbol: php_pdo_int64_to_str in Unknown on line 0
[] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u14 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
` 

but i have this file `/usr/lib/php5/20100525/pdo_sqlrelay.so` present in that same location

**Comment by angusfz** [comment]
Hi
Maybe you should  try to manual add /usr/local/sqlrelay/lib  path in /etc/ld.so.conf, and use ldconfig to reload lib
